spring:
  config:
    activate:
      on-profile:
        - test
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      use_sql_comment: false
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${TEST_DB_URL}
    port: 3306
    username: ${TEST_DB_ID}
    password: ${TEST_DB_PW}
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema:
        - classpath:schema.sql
