spring:
  config:
    activate:
      on-profile:
        - test
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      use_sql_comment: false
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/anabada-test?createDatabaseIfNotExist=true"
    port: 3306
    username: "root"
    password: "test1234"
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema:
        - classpath:schema.sql